steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |
          echo
          echo "**********************************************"
          echo "* Set backend project Id *"
          echo "**********************************************"
          echo

          gcloud config set project ${_PROJECT_ID}
          gcloud config set compute/region ${_PROJECT_REGION}

          echo
          echo "**************************************"
          echo "* Replace variables in .firebaserc file *"
          echo "**************************************"
          echo

          awk '{gsub(/<PROJECT_ID>/,"'${_PROJECT_ID}'")}1' /workspace/.firebaserc > /workspace/tmp.firebaserc && mv /workspace/tmp.firebaserc /workspace/.firebaserc


  - id: Build and deploy
    name: node:10.22-alpine
    entrypoint: sh
    args:
      - '-c'
      - |

          echo
          echo "**************************************"
          echo "* Install Modules *"
          echo "**************************************"
          echo

          npm install -g firebase-tools

          cd ./functions
          npm install

          echo
          echo "**************************************"
          echo "* Deploy Functions *"
          echo "**************************************"
          echo

          firebase deploy --only functions --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}

          echo
          echo "**************************************"
          echo "* Deploy Firestore Rules *"
          echo "**************************************"
          echo

          firebase deploy --only firestore:rules --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}

          echo
          echo "**************************************"
          echo "* Deploy Storage Rules *"
          echo "**************************************"
          echo

          firebase deploy --only storage:rules --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}